version: 2
jobs:
  build:
    docker:
      - image: clojure:openjdk-11-lein-slim-buster
        auth:
          username: victorbjelkholm
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: apt update && apt install -y make curl tar
      - run: make test
