version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
        auth:
          username: victorbjelkholm
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: sudo apt update && sudo apt install -y make
      - run: make test
